#!/bin/sh 

bg_color=#2f343f 
text_color=#f3f4f5 
htext_color=#9575cd 
transparent=#992f343f 

rofi -combi-modi window,run,drun -show combi -lines 10 -eh 1 -width 30 -padding 150 -bw 0 -color-window "$transparent, $transparent, $transparent" -color-normal "$transparent, $text_color, $transparent, $bg_color, $htext_color" -font "System San Francisco Display 16"
#rofi -show run -lines 5 -eh 2 -width 30 -padding 120 -bw 0 -font "System San Francisco Display 16"
#rofi.theme: ~/.cache/wal/colors-rofi-dark.rasi
rofi.theme: ~/.cache/wal/colors-rofi-light.rasi